################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SRC_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CPP_SRCS := 
C++_UPPER_SRCS := 
SRC_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CC_UPPER_SRCS := 
CXX_SRCS := 
CPP_UPPER_SRCS := 
C++_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
S_SRCS := 
X_SRCS := 
CC_SRCS := 
CXX_UPPER_SRCS := 
OBJS := 
C++_UPPER_DEPS := 
C_DEPS := 
X_DEPS := 
O_DEPS := 
S_DEPS := 
CXX_DEPS := 
S_UPPER_DEPS := 
C++_DEPS := 
SRC_DEPS := 
ASM_DEPS := 
CC_DEPS := 
LINKER_OUTPUT_OUTPUTS := 
SRC_UPPER_DEPS := 
OBJCOPY_OUTPUTTYPE_OUTPUTS := 
CPP_UPPER_DEPS := 
OBJ_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
CPP_DEPS := 
CC_UPPER_DEPS := 
C_UPPER_DEPS := 
CXX_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources/ProductModules/PM_SwTimersCounters \
Sources/ProductModules/PM_SWalarms \
Sources/ProductModules/PM_ProfileLoadsPartialization \
Sources/ProductModules/PM_Library \
Sources/ProductModules/PM_FreqFeedbacks \
Sources/ProductModules/PM_EnergyMeterSw \
Sources/ProductModules/PM_DigitalOutputMulti \
Sources/ProductModules/PM_Consistency \
Sources/ProductModules/PM_BusCOMM \
Sources/ProductModules/PM_AnalogFeedbacks \
Sources/PlatformLibrary/LIB_notify \
Sources/PlatformLibrary/LIB_ZeroCrossing \
Sources/PlatformLibrary/LIB_ZcLoads \
Sources/PlatformLibrary/LIB_Setting \
Sources/PlatformLibrary/LIB_SecurityCheck \
Sources/PlatformLibrary/LIB_Reset \
Sources/PlatformLibrary/LIB_IOManager \
Sources/PlatformLibrary/LIB_GridVoltage \
Sources/PlatformLibrary/LIB_Generic \
Sources/PlatformLibrary/LIB_Feedbacks \
Sources/PlatformLibrary/LIB_Error \
Sources/PlatformLibrary/LIB_DigitalIO \
Sources/PlatformLibrary/LIB_BackUp \
Sources/PlatformLibrary/LIB_Analog \
Sources/Main/EmbOS/tools \
Sources/Main/EmbOS/Services/ActivityList \
Sources/Main/EmbOS \
Sources/Inertia/General \
Sources/HAL/RN_RX200 \
Sources/HAL/RN_RX200/McuModule \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/Voltage \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/Temperature \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/ROM \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/RAM \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/POE \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/IWDT \
Sources/HAL/RN_RX200/IEC60335_B_libs/src \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/Clock \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/CPU \
Sources/HAL/RN_RX200/IEC60335_B_libs/src/ADC12 \
Sources/HAL/RN_RX200/EmbOS \
Sources/Drivers/SWDMA \
Sources/Drivers/SWCRC \
Sources/Drivers/OCWDT \
Sources/Drivers/OCUART \
Sources/Drivers/OCTPM \
Sources/Drivers/OCSPI \
Sources/Drivers/OCRTC \
Sources/Drivers/OCRST \
Sources/Drivers/OCLVD \
Sources/Drivers/OCIRQ \
Sources/Drivers/OCI2C \
Sources/Drivers/OCFLS \
Sources/Drivers/OCDMA \
Sources/Drivers/OCDIO \
Sources/Drivers/OCCRC \
Sources/Drivers/OCCLK \
Sources/Drivers/OCADC \
Sources/CFG_DishWasher/CFG_Inertia \

