/* file: proctask.c, automatically generated by GENH8.EXE, Version: 3.05 */
/* from: C:\PROGETTI\RTC_DEA700_2_STEP_DEV\CFG_DISHWASHER\OSGEN\OSEK\H8\DW_DEA700_H8.oil */
/* at  : Thu Sep 06 16:46:04 2012 */
/* Implementation: HitachiH8_3687Group */
/* Version of general code: 3.33a */

#include <vrm.h>
#define osdVrmGenMajRelNum 3
#define osdVrmGenMinRelNum 5
#include <vrm.h>

#include <osek.h>
#include <osekext.h>

#define osdProcSupportNone 0
#define osdProcSupportC    1
#define osdProcSupportAsm  2
#define osdProcSupport     osdProcSupportNone


/* variables for assertions */
#if osdEnableProcedures
#if osdEnableAssertions
#if (osdNumberOfAllTasks>0)
   osqBOOL1 osqBOOL2 osBoolArrayBaseType osqBOOL3 osIsInProcedure[osdNumberOfAllTasks];
#else
   osqBOOL1 osqBOOL2 osBoolArrayBaseType osqBOOL3 osIsInProcedure[1];
#endif
#endif
#endif
/*** full preemptive tasks (have C part only) ***/

/*** non preemptive task or task with internal resource (can have C or Asm part) ***/


/* END OF C:\PROGETTI\RTC_Dea700_2_STEP_dev\CFG_DishWasher\OSgen\OSEK\H8\proctask.c */

