; file: tcb_inc.h, automatically generated by GENH8.EXE, Version: 3.05
; from: C:\PROGETTI\RTC_DEA700_2_STEP_DEV\CFG_DISHWASHER\OSGEN\OSEK\H8\DW_DEA700_H8.oil
; at  : Thu Sep 06 16:46:04 2012
; Implementation: HitachiH8_3687Group
; Version of general code: 3.33a

   osdLib: .ASSIGNA 0
   CC: .ASSIGNC "ECC1"

   STATUS_LEVEL: .ASSIGNC "EXTENDED_STATUS"

   osdFullPreempt: .ASSIGNC "0"
   osdMixedPreempt: .ASSIGNC "1"
   osdNonPreempt: .ASSIGNC "0"

   osdNumberOfAllTasks: .ASSIGNA 14
   osdNumberOfBasicTasks: .ASSIGNA 13
   osdNumberOfExtendedTasks: .ASSIGNA 1
   osdNumberOfPriorities: .ASSIGNA 18
   osdNumberOfAllResources: .ASSIGNA 4
   osdNumberOfTaskResources: .ASSIGNA 4
   osdNumberOfInterruptResources: .ASSIGNA 0
   osdNumberOfInternalResources: .ASSIGNA 0
   osdNumberOfAlarms: .ASSIGNA 12
   osdNumberOfVarAlarms: .ASSIGNA 12
   osdNumberOfVarHeapAlarms: .ASSIGNA 12
   osdNumberOfStatHeapAlarms: .ASSIGNA 0
   osdNumberOfAlarmCallback: .ASSIGNA 3
   osdNumberOfAlarmSetEvent: .ASSIGNA 0
   osdNumberOfAlarmActivateTask: .ASSIGNA 9
   osdNumberOfCounters: .ASSIGNA 1
   osdUseCounterAPI: .ASSIGNA 0
   osdStackCheck: .ASSIGNC "1"

   osdSuppressFilenames: .ASSIGNC "1"

   osdEnableAssertions: .ASSIGNC "0"

   osdORTIDebug: .ASSIGNA 0
   osdORTIVersion: .ASSIGNA 210

   osdORTIEnabled: .ASSIGNA 0

   osdEnableProcedures: .ASSIGNA 0

   osdEnableContextOverlay: .ASSIGNA 0

   osdNumberOfAppModes: .ASSIGNA 3

   OSDEFAULTAPPMODE: .ASSIGNC "0x01"
   NormalMode: .ASSIGNC "0x02"
   ProgrammingMode: .ASSIGNC "0x04"

   osdOSEK2_2: .ASSIGNC "1"

   osdOSEKVersionSpec: .ASSIGNA 220

   osdGetServiceIdMacros: .ASSIGNC "1"
   osdParameterAccessMacros: .ASSIGNC "0"

   osdAdvancedMode: .ASSIGNA 24
osdRomPtr: .DEFINE "24"
   osdUseHighResolutionTimer: .ASSIGNA 1
; max(number of priority,number of tasks)

   osdRTSize: .ASSIGNA 2

   osdErrorHook: .ASSIGNC "1"
   osdPreTaskHook: .ASSIGNC "0"
   osdPostTaskHook: .ASSIGNC "0"
   osdStartupHook: .ASSIGNC "0"
   osdShutdownHook: .ASSIGNC "0"
; Tasks


; Resources





; Counter

   SystemTimer: .ASSIGNA 0


; Events

; AUTO
; AUTO
; Alarms

; Maximum possible allowed value of the system counter in ticks
   OSMAXALLOWEDVALUE: .ASSIGNC "0x3fffffffUL"

; Minimum allowed number of ticks for a cyclic alarm
   OSMINCYCLE: .ASSIGNA 1

; Number of ticks required to reach specific unit of the system counter
   OSTICKSPERBASE: .ASSIGNA 1




; ISRs

   osdIsrZC_InterruptCat: .ASSIGNA 2
   osdIsrIsr_I2CCat: .ASSIGNA 2
   osdIsrStartupCodeCat: .ASSIGNA 1
   osdIsrUartRx_InterruptCat: .ASSIGNA 2
   osdIsrIsr_Tpm2OverflowCat: .ASSIGNA 2
   osdIsrIsr_NMICat: .ASSIGNA 1

; END OF C:\PROGETTI\RTC_Dea700_2_STEP_dev\CFG_DishWasher\OSgen\OSEK\H8\tcb_inc.h

