/*
 * Automatically generated C config: don't edit
 * Dist builder
 * Tue May 14 14:49:36 2013
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MANAGE_AD_CHANNEL_READ_SUPPORT_ENABLE 1
#define CONFIG_PM_PROFILE_LOADS_PARTIALIZATION_SUPPORT 1
#define CONFIG_ADC_DRV_CHANNELS_NUM 1
#define CONFIG_MAIN_ANALOGINPUTS_TASK_STACK_SIZE 192
#define CONFIG_PM_ANALOG_FEEDBACKS_SUPPORT 1
#define CONFIG_EXTERNAL_COMMAND_BUFFER_HDR_SZ 2
#define CONFIG_BLDC_DRAIN_L_SUPPORT 1
#define CONFIG_FEEDBACK_ENABLE 1
#define CONFIG_VLINEMEASURE_NUM_OF_SAMPLES 5
#define CONFIG_IOM_EXT_CMDDATA_RAM_READ_SZ 4
#define CONFIG_VLINEMEASURE_COMPENSATION_AD 15
#define CONFIG_EXT_LOAD_PARAMDATA_SZ 10
#define CONFIG_FDB_NO_ZC_LIMIT_FOR_FREQ 2
#define CONFIG_FDB_ZC_LIMIT_FOR_FREQ 14
#define CONFIG_APPLIANCE_DW 1
#define CONFIG_HAL_CLK_FIXED_20MHZ 1
#define CONFIG_BLDC_WASH_L_CMD_SZ 6
#define CONFIG_FEEDBACK_SAMPLES 16
#define CONFIG_MAIN_NORMAL_FEEDBACKS_READ_ENABLE 1
#define CONFIG_MAIN_SUPERVISOR_TASK_STACK_SIZE 80
#define CONFIG_IOM_EXT_CMDDATA_RAM_WRITE_SZ 4
#define CONFIG_IOM_EXT_CMDDATA_EXTRA_REQ_SZ 2
#define CONFIG_FDB_NO_ZC_LIMIT_FOR_LEVEL 14
#define CONFIG_IOM_EXT_CMDDATA_AW_HDR_SZ 1
#define CONFIG_FDB_ZC_LIMIT_FOR_LEVEL 14
#define CONFIG_MAIN_MEASURELIVE_TASK_STACK_SIZE 160
#define CONFIG_MAIN_OUTPUTS_TASK_STACK_SIZE 64
#define CONFIG_MAIN_LIVE_UPDATE_ZC_LINE_VOLTAGE 1
#define CONFIG_BLDC_DRAIN_L_CMD_SZ 6
#define CONFIG_N_FEEDBACK 1
#define CONFIG_PM_ANALOG_FEEDBACKS_NUM 8
#define CONFIG_MAIN_DELAYED_FEEDBACKS_READ_ENABLE 1
#define CONFIG_LIB_SETTING_CHECK_TYPE_CHK 1
#define CONFIG_LIB_ANALOG 1
#define CONFIG_BLDC_WASH_L_SUPPORT 1
#define CONFIG_LIB_EXTERNAL_BOARD_SUPPORT 1
#define CONFIG_MAIN_FEEDBACKS_TASK_STACK_SIZE 32
#define CONFIG_PL_DRV_OCI2C_USE_CUSTOM_RESET 1
